### ISSUE TITLE
Cannot remove tutorial from history

### ISSUE THREAD

**Issue by vlad2305m** [stephtr/qalculator#12]
Every time I refresh the app, missing tutorial examples get added to the back of the history.

**Comment by stephtr** [comment]
Yes, that's a leftover from adding a tutorial example and wanting users' history to include them.

**Comment by stephtr** [comment]
fixed by https://github.com/stephtr/qalculator/commit/6f7e85166d7617b3c01a9e9ca7bf8ffe2ebd511c
