### ISSUE TITLE
Variables change while typing in the input field

### ISSUE THREAD

**Issue by vlad2305m** [stephtr/qalculator#13]
Expected:
Only change variables after pressing enter.
Reproduction:
1. Type `x=2`
2. Hit `Enter`
3. Type `x=`
4. Backspace
5. See that `x` is now `0`

**Comment by vlad2305m** [comment]
Possible solutions:
- Don't preview prompts containing `=`
- Spawn a new qalc, feed the history of the current session into it, and use it for preview instead. (Only in special cases)

**Comment by stephtr** [comment]
Good point 💪 Did it now with a regex to filter out any combination of "variableName =", since it should be still able to solve "x - 3 = 0" inline.

**Comment by stephtr** [comment]
Fixed by https://github.com/stephtr/qalculator/commit/b96310db8b9a7ae7c170d743b6696f52b8f26a4d
