### ISSUE TITLE
Calculations with the same prompt, but different result are not properly added to the history

### ISSUE THREAD

**Issue by vlad2305m** [stephtr/qalculator#15]
**Expected:**
Be able to choose to either save unique prompts or save unique prompt-result pairs to the history.
**Reproduction:**
1. `x=0`
2. `x=x+1`
3. `x=x+1`
...

**Comment by stephtr** [comment]
For me that use case is too uncommon to add a separate setting for that. Since the main idea of the history was to be able to recall calculations, I'll keep it as is for now. If there's a good use case, I might change my opinion.
