### ISSUE TITLE
Currency Conversion

### ISSUE THREAD

**Issue by abhishekmj303** [stephtr/qalculator#16]
Are there any plans to support currency conversion? Currently it just says:
```
Trailing characters "usd" (not a valid variable/function/unit) in number "1usd" were ignored.
```

**Comment by stephtr** [comment]
I was trying to find some time for it, but no. It's currently not on the list. Having to update the conversion rate while still being able to use the functionality offline is too much work for me for now.

Just in case I'd start working on it: The easiest route I see is adding a server endpoint which calls [takes data from the ECB](https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml) and whose fetch gets cached via the client's service worker. The client side JS will then async inject the conversion rates into the wasm object.

**Comment by stephtr** [comment]
The newest version now includes currency conversion. It might take up to 1 h (or in the worst case 24 h) until the updated DNS settings make that feature available.
