### ISSUE TITLE
site down?

### ISSUE THREAD

**Issue by nicoleahmed** [stephtr/qalculator#17]
Hi Stephan
This looks like great work

Is the web version 'https://qalculator.xyz/' down?

I've tried on a few devices here in the North East of England.

Thanks
Nicole

**Comment by stephtr** [comment]
No, it should actually be up. Do you still have issues?
Stephan

**Comment by nicoleahmed** [comment]
It's working for me now thanks. Not sure what happened before but it's working on my phone when previously it wasn't

Thanks
