### ISSUE TITLE
Porting To Ticwatch?

### ISSUE THREAD

**Issue by Lyunko** [stephtr/qalculator#18]
Hello there, this app has saved me a whole lotta time from calculating units for my job, thanks a bunch for making this app and making it completely free!
Also... I am not good at porting and this stuff is new to me.... but please hear me out on this small request. I think it might be convenient to port this app to be suitable for the ticwatch and I mean it'd be nice to have a calculator in a small factored form.

**Comment by stephtr** [comment]
Hi, nice that the app is also useful for you!
I don't see a straightforward way to port this app to the ticwatch, it would most probably be easier to start with a new app from scratch, based on [libqalculate](https://github.com/Qalculate/libqalculate).
