### ISSUE TITLE
Add to f-droid

### ISSUE THREAD

**Issue by Markus40** [stephtr/qalculator#24]
I like to get my apps from F-Droid. Would it be possible to host this app on the F-Droid store?

**Comment by stephtr** [comment]
Hi,

I briefly looked through their [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/). To me, it seems as if the PWA-in-App-Store approach doesn't really work well with their goals. Updates in our case are usually not shipped via the store, but via the web server hosting the progressive web app (PWA).

Alternatively, you can also install Qalculator.xyz as a PWA using your web browser.

**Comment by stephtr** [comment]
In case it helps you, I just made the APK file itself available: https://github.com/stephtr/qalculator/releases/tag/android-2
