### ISSUE TITLE
Can i download APK?

### ISSUE THREAD

**Issue by SeryiBaran** [stephtr/qalculator#26]
Hello! Can i download apk without using "download apk from google play" sites?

BTW: Qalculator is veeeery cool project!

**Comment by SeryiBaran** [comment]
OH! Readed about PWA in #24. Thanks!

**Comment by stephtr** [comment]
Ah but what I could actually do is providing an APK, additionally to Qalculator being a PWA.

**Comment by SeryiBaran** [comment]
That would be super, thanks!

**Comment by stephtr** [comment]
I released it under https://github.com/stephtr/qalculator/releases/tag/android-2
Let me know in case that doesn't work.

**Comment by SeryiBaran** [comment]
All works perfectly (BQ 6051g), big thanks! ❤️❤️

**Comment by stephtr** [comment]
Perfect, thank you too!
