### ISSUE TITLE
how to use currency units?

### ISSUE THREAD

**Issue by tenturestept** [stephtr/qalculator#27]
currently i get the following when trying to use a currency:

<img width="823" alt="example" src="https://github.com/user-attachments/assets/7dd3e0ef-c63a-4ca6-bb45-c9d624e96d10">

**Comment by stephtr** [comment]
Thanks, there was actually a bug in the code which prevented cached currencies from being loaded. Fixed by e211c1e99fa9cbe6ac0499d5423c8ce3ddfa486c
As soon as your qalculator gets updated on your machine (it should show you a prompt after you leave it open for a few seconds), it should be fixed.

**Comment by tenturestept** [comment]
Thank you!
